import type { LanguageCode } from '@/lib/i18n';

export const terms: Record<LanguageCode, string> = {
  en: `# Terms of Use

**Last updated: 2026**

## 1. What this is
RoastBack.app is an early, free beta ("v0"). You upload a photo, an AI generates a humorous "roast" about it, and you can reply to argue with it. This is experimental software, not a finished commercial product.

## 2. Your content
You're responsible for what you upload. Don't upload photos containing nudity, violence, illegal content, or images of other identifiable people without their consent. Uploaded photos are automatically screened before analysis, and flagged images are rejected.

## 3. Age requirement
You must be at least 16 years old (or the age of digital consent in your country, if higher) to use this service.

## 4. AI-generated content
The "roast" text is generated by an AI model for entertainment purposes. It's a playful, subjective take - not a factual assessment of you, your belongings, or your life. Don't take it too seriously.

## 5. No guarantee of availability
This is a free beta with a limited budget. The service may pause or stop at any time without notice, including if daily usage costs are exhausted. We don't guarantee uptime, availability, or that the service will continue to exist.

## 6. No warranty
The service is provided "as is," without warranties of any kind. We're not liable for any damages arising from your use of it.

## 7. Changes
We may update these terms as the product evolves. Continued use after changes means you accept the updated terms.

## 8. Contact
Questions? Email allbeanskey@gmail.com.
`,
  pl: `# Regulamin

**Ostatnia aktualizacja: 2026**

## 1. Czym jest ta appka
RoastBack.app to wczesna, darmowa wersja testowa ("v0"). Wgrywasz zdjęcie, AI generuje z niego żartobliwy "roast", a Ty możesz się z nim pokłócić. To eksperymentalne oprogramowanie, nie gotowy produkt komercyjny.

## 2. Twoja treść
Odpowiadasz za to, co wgrywasz. Nie wgrywaj zdjęć zawierających nagość, przemoc, treści nielegalne ani wizerunku innych, rozpoznawalnych osób bez ich zgody. Wgrane zdjęcia są automatycznie sprawdzane przed analizą, a oznaczone jako niedopuszczalne - odrzucane.

## 3. Wymóg wieku
Musisz mieć co najmniej 16 lat (lub wiek zgody cyfrowej obowiązujący w Twoim kraju, jeśli jest wyższy), żeby korzystać z tej usługi.

## 4. Treści generowane przez AI
Tekst "roastu" jest generowany przez model AI w celach rozrywkowych. To żartobliwa, subiektywna opinia - nie faktyczna ocena Ciebie, Twoich rzeczy czy życia. Nie bierz tego zbyt poważnie.

## 5. Brak gwarancji dostępności
To darmowa wersja testowa z ograniczonym budżetem. Usługa może zostać wstrzymana lub zatrzymana w dowolnym momencie bez uprzedzenia, w tym gdy wyczerpie się dzienny budżet. Nie gwarantujemy dostępności ani dalszego istnienia usługi.

## 6. Brak rękojmi
Usługa jest dostarczana "tak jak jest", bez żadnych gwarancji. Nie ponosimy odpowiedzialności za szkody wynikające z korzystania z niej.

## 7. Zmiany
Możemy aktualizować ten regulamin w miarę rozwoju produktu. Dalsze korzystanie po zmianach oznacza akceptację nowej wersji.

## 8. Kontakt
Pytania? Napisz na allbeanskey@gmail.com.
`,
  de: `# Nutzungsbedingungen

**Zuletzt aktualisiert: 2026**

## 1. Worum es geht
RoastBack.app ist eine frühe, kostenlose Beta-Version ("v0"). Du lädst ein Foto hoch, eine KI erstellt einen humorvollen "Roast" darüber, und du kannst darauf antworten. Dies ist experimentelle Software, kein fertiges kommerzielles Produkt.

## 2. Deine Inhalte
Du bist verantwortlich für das, was du hochlädst. Lade keine Fotos mit Nacktheit, Gewalt, illegalen Inhalten oder Bildern anderer identifizierbarer Personen ohne deren Zustimmung hoch. Hochgeladene Fotos werden vor der Analyse automatisch geprüft, markierte Bilder werden abgelehnt.

## 3. Altersanforderung
Du musst mindestens 16 Jahre alt sein (oder das digitale Einwilligungsalter deines Landes, falls höher).

## 4. KI-generierte Inhalte
Der "Roast"-Text wird von einem KI-Modell zu Unterhaltungszwecken erstellt. Es ist eine spielerische, subjektive Einschätzung - keine sachliche Bewertung von dir, deinem Besitz oder deinem Leben.

## 5. Keine Verfügbarkeitsgarantie
Dies ist eine kostenlose Beta mit begrenztem Budget. Der Dienst kann jederzeit ohne Vorankündigung pausiert oder eingestellt werden, auch wenn das Tagesbudget aufgebraucht ist.

## 6. Keine Gewährleistung
Der Dienst wird "wie besehen" bereitgestellt, ohne jegliche Garantien. Wir haften nicht für Schäden aus der Nutzung.

## 7. Änderungen
Wir können diese Bedingungen im Zuge der Produktentwicklung aktualisieren. Die weitere Nutzung nach Änderungen bedeutet Zustimmung.

## 8. Kontakt
Fragen? Schreib an allbeanskey@gmail.com.
`,
  fr: `# Conditions d'utilisation

**Dernière mise à jour : 2026**

## 1. Ce que c'est
RoastBack.app est une bêta précoce et gratuite ("v0"). Tu télécharges une photo, une IA génère un "roast" humoristique à son sujet, et tu peux lui répondre. Il s'agit d'un logiciel expérimental, pas d'un produit commercial fini.

## 2. Ton contenu
Tu es responsable de ce que tu télécharges. Ne télécharge pas de photos contenant de la nudité, de la violence, du contenu illégal, ou des images d'autres personnes identifiables sans leur consentement. Les photos téléchargées sont automatiquement vérifiées avant analyse.

## 3. Âge requis
Tu dois avoir au moins 16 ans (ou l'âge de consentement numérique de ton pays, si supérieur).

## 4. Contenu généré par IA
Le texte du "roast" est généré par un modèle d'IA à des fins de divertissement. C'est une opinion ludique et subjective - pas une évaluation factuelle de toi, de tes affaires ou de ta vie.

## 5. Aucune garantie de disponibilité
Il s'agit d'une bêta gratuite avec un budget limité. Le service peut être suspendu ou arrêté à tout moment sans préavis, y compris si le budget quotidien est épuisé.

## 6. Aucune garantie
Le service est fourni "tel quel", sans garantie d'aucune sorte. Nous ne sommes pas responsables des dommages résultant de son utilisation.

## 7. Modifications
Nous pouvons mettre à jour ces conditions au fil de l'évolution du produit. Continuer à utiliser le service après des modifications signifie que tu les acceptes.

## 8. Contact
Des questions ? Écris à allbeanskey@gmail.com.
`,
  es: `# Términos de uso

**Última actualización: 2026**

## 1. Qué es esto
RoastBack.app es una beta temprana y gratuita ("v0"). Subes una foto, una IA genera un "roast" humorístico sobre ella, y puedes responderle. Esto es software experimental, no un producto comercial terminado.

## 2. Tu contenido
Eres responsable de lo que subes. No subas fotos con desnudez, violencia, contenido ilegal, o imágenes de otras personas identificables sin su consentimiento. Las fotos subidas se revisan automáticamente antes del análisis.

## 3. Requisito de edad
Debes tener al menos 16 años (o la edad de consentimiento digital de tu país, si es mayor).

## 4. Contenido generado por IA
El texto del "roast" es generado por un modelo de IA con fines de entretenimiento. Es una opinión juguetona y subjetiva - no una evaluación real de ti, tus pertenencias o tu vida.

## 5. Sin garantía de disponibilidad
Esta es una beta gratuita con presupuesto limitado. El servicio puede pausarse o detenerse en cualquier momento sin previo aviso, incluso si se agota el presupuesto diario.

## 6. Sin garantías
El servicio se ofrece "tal cual", sin garantías de ningún tipo. No somos responsables de los daños derivados de su uso.

## 7. Cambios
Podemos actualizar estos términos a medida que el producto evoluciona. Seguir usando el servicio después de los cambios implica aceptarlos.

## 8. Contacto
¿Preguntas? Escribe a allbeanskey@gmail.com.
`,
};